import Foundation

/// Protocol defining common fields for central challenge requests.
public protocol AbstractCentralChallengeRequest: Message {
    /// Identifier for the app instance initiating pairing.
    var appInstanceId: Int { get }
    /// Random challenge generated by the central (app).
    var centralChallenge: Data { get }
}
