//
//  AbstractCentralChallengeRequest.swift
//  TandemKit
//
//  Created by OpenAI's ChatGPT.
//
//  Mirrors PumpX2's AbstractCentralChallengeRequest providing a common interface
//  for authorization messages that include an app instance identifier and
//  central challenge payload.
//

import Foundation

/// Protocol defining common fields for central challenge requests.
public protocol AbstractCentralChallengeRequest: Message {
    /// Identifier for the app instance initiating pairing.
    var appInstanceId: Int { get }
    /// Random challenge generated by the central (app).
    var centralChallenge: Data { get }
}

