//
//  MessageRegistry.swift
//  Generated by automation in CLI task.
//

import Foundation

public struct MessageMetadata: Sendable {
    public let type: Message.Type
    public let name: String
    public let opCode: UInt8
    public let size: Int
    public let messageType: MessageType
    public let characteristic: CharacteristicUUID
    public let signed: Bool
    public let variableSize: Bool
    public let stream: Bool
    public let modifiesInsulinDelivery: Bool

    init?(type: Message.Type) {
        let props = type.props
        if props.opCode == 0 {
            return nil
        }
        self.type = type
        self.name = String(describing: type)
        self.opCode = props.opCode
        self.size = Int(props.size)
        self.messageType = props.type
        self.characteristic = props.characteristic
        self.signed = props.signed
        self.variableSize = props.variableSize
        self.stream = props.stream
        self.modifiesInsulinDelivery = props.modifiesInsulinDelivery
    }

    public func matches(payloadLength: Int) -> Bool {
        if stream || variableSize {
            return true
        }
        if payloadLength == size {
            return true
        }
        if signed && payloadLength == size + 24 {
            return true
        }
        if size == 0 && payloadLength == 0 {
            return true
        }
        if signed && size == 0 && payloadLength == 24 {
            return true
        }
        return false
    }
}

public enum MessageRegistry {
    private static let allTypes: [Message.Type] = [
        AlarmStatusRequest.self,
        AlarmStatusResponse.self,
        AlertStatusRequest.self,
        AlertStatusResponse.self,
        ApiVersionRequest.self,
        ApiVersionResponse.self,
        BasalIQAlertInfoRequest.self,
        BasalIQAlertInfoResponse.self,
        BasalIQSettingsRequest.self,
        BasalIQSettingsResponse.self,
        BasalIQStatusRequest.self,
        BasalIQStatusResponse.self,
        BasalLimitSettingsRequest.self,
        BasalLimitSettingsResponse.self,
        BolusCalcDataSnapshotRequest.self,
        BolusCalcDataSnapshotResponse.self,
        BolusPermissionChangeReasonRequest.self,
        BolusPermissionChangeReasonResponse.self,
        BolusPermissionReleaseRequest.self,
        BolusPermissionReleaseResponse.self,
        BolusPermissionRequest.self,
        BolusPermissionResponse.self,
        CGMAlertStatusRequest.self,
        CGMAlertStatusResponse.self,
        CGMGlucoseAlertSettingsRequest.self,
        CGMGlucoseAlertSettingsResponse.self,
        CGMHardwareInfoRequest.self,
        CGMHardwareInfoResponse.self,
        CGMOORAlertSettingsRequest.self,
        CGMOORAlertSettingsResponse.self,
        CGMRateAlertSettingsRequest.self,
        CGMRateAlertSettingsResponse.self,
        CGMStatusRequest.self,
        CGMStatusResponse.self,
        CancelBolusRequest.self,
        CancelBolusResponse.self,
        CentralChallengeRequest.self,
        CentralChallengeResponse.self,
        ChangeControlIQSettingsRequest.self,
        ChangeControlIQSettingsResponse.self,
        ChangeTimeDateRequest.self,
        ChangeTimeDateResponse.self,
        CommonSoftwareInfoRequest.self,
        CommonSoftwareInfoResponse.self,
        ControlIQIOBRequest.self,
        ControlIQIOBResponse.self,
        ControlIQInfoAbstractResponse.self,
        ControlIQInfoV1Request.self,
        ControlIQInfoV2Request.self,
        ControlIQSleepScheduleRequest.self,
        ControlIQSleepScheduleResponse.self,
        CreateIDPRequest.self,
        CreateIDPResponse.self,
        CurrentBasalStatusRequest.self,
        CurrentBasalStatusResponse.self,
        CurrentBatteryV1Request.self,
        CurrentBatteryV1Response.self,
        CurrentBatteryV2Request.self,
        CurrentBatteryV2Response.self,
        CurrentBolusStatusRequest.self,
        CurrentBolusStatusResponse.self,
        CurrentEGVGuiDataRequest.self,
        CurrentEGVGuiDataResponse.self,
        DeleteIDPRequest.self,
        DeleteIDPResponse.self,
        DetectingCartridgeStateStreamResponse.self,
        DisconnectPumpRequest.self,
        DisconnectPumpResponse.self,
        DismissNotificationRequest.self,
        DismissNotificationResponse.self,
        EnterChangeCartridgeModeRequest.self,
        EnterChangeCartridgeModeResponse.self,
        EnterChangeCartridgeModeStateStreamResponse.self,
        EnterFillTubingModeRequest.self,
        EnterFillTubingModeResponse.self,
        ExitChangeCartridgeModeRequest.self,
        ExitChangeCartridgeModeResponse.self,
        ExitFillTubingModeRequest.self,
        ExitFillTubingModeResponse.self,
        ExitFillTubingModeStateStreamResponse.self,
        ExtendedBolusStatusRequest.self,
        ExtendedBolusStatusResponse.self,
        FillCannulaRequest.self,
        FillCannulaResponse.self,
        FillCannulaStateStreamResponse.self,
        FillTubingStateStreamResponse.self,
        GetG6TransmitterHardwareInfoRequest.self,
        GetG6TransmitterHardwareInfoResponse.self,
        GetSavedG7PairingCodeRequest.self,
        GetSavedG7PairingCodeResponse.self,
        GlobalMaxBolusSettingsRequest.self,
        GlobalMaxBolusSettingsResponse.self,
        HistoryLogRequest.self,
        HistoryLogResponse.self,
        HistoryLogStatusRequest.self,
        HistoryLogStatusResponse.self,
        HistoryLogStreamResponse.self,
        HomeScreenMirrorRequest.self,
        HomeScreenMirrorResponse.self,
        IDPSegmentRequest.self,
        IDPSegmentResponse.self,
        IDPSettingsRequest.self,
        IDPSettingsResponse.self,
        InitiateBolusRequest.self,
        InitiateBolusResponse.self,
        InsulinStatusRequest.self,
        InsulinStatusResponse.self,
        Jpake1bRequest.self,
        Jpake1bResponse.self,
        Jpake2Request.self,
        Jpake2Response.self,
        Jpake3SessionKeyRequest.self,
        Jpake3SessionKeyResponse.self,
        Jpake4KeyConfirmationRequest.self,
        Jpake4KeyConfirmationResponse.self,
        LastBGRequest.self,
        LastBGResponse.self,
        LastBolusStatusRequest.self,
        LastBolusStatusResponse.self,
        LastBolusStatusV2Request.self,
        LastBolusStatusV2Response.self,
        LocalizationRequest.self,
        LocalizationResponse.self,
        MalfunctionStatusRequest.self,
        MalfunctionStatusResponse.self,
        NonControlIQIOBRequest.self,
        NonControlIQIOBResponse.self,
        NonexistentDetectingCartridgeStateStreamRequest.self,
        NonexistentEnterChangeCartridgeModeStateStreamRequest.self,
        NonexistentExitFillTubingModeStateStreamRequest.self,
        NonexistentFillCannulaStateStreamRequest.self,
        NonexistentFillTubingStateStreamRequest.self,
        NonexistentHistoryLogStreamRequest.self,
        NonexistentPumpingStateStreamRequest.self,
        OtherNotification2StatusRequest.self,
        OtherNotification2StatusResponse.self,
        OtherNotificationStatusRequest.self,
        OtherNotificationStatusResponse.self,
        PlaySoundRequest.self,
        PlaySoundResponse.self,
        ProfileStatusRequest.self,
        ProfileStatusResponse.self,
        PumpChallengeRequest.self,
        PumpChallengeResponse.self,
        PumpFeaturesAbstractResponse.self,
        PumpFeaturesV1Request.self,
        PumpFeaturesV1Response.self,
        PumpFeaturesV2Request.self,
        PumpFeaturesV2Response.self,
        PumpGlobalsRequest.self,
        PumpGlobalsResponse.self,
        PumpSettingsRequest.self,
        PumpSettingsResponse.self,
        PumpVersionRequest.self,
        PumpVersionResponse.self,
        PumpingStateStreamResponse.self,
        ReminderStatusRequest.self,
        ReminderStatusResponse.self,
        RemindersRequest.self,
        RemindersResponse.self,
        RemoteBgEntryRequest.self,
        RemoteBgEntryResponse.self,
        RemoteCarbEntryRequest.self,
        RemoteCarbEntryResponse.self,
        RenameIDPRequest.self,
        RenameIDPResponse.self,
        ResumePumpingRequest.self,
        ResumePumpingResponse.self,
        SetActiveIDPRequest.self,
        SetActiveIDPResponse.self,
        SetDexcomG7PairingCodeRequest.self,
        SetDexcomG7PairingCodeResponse.self,
        SetG6TransmitterIdRequest.self,
        SetG6TransmitterIdResponse.self,
        SetIDPSegmentRequest.self,
        SetIDPSegmentResponse.self,
        SetIDPSettingsRequest.self,
        SetIDPSettingsResponse.self,
        SetMaxBasalLimitRequest.self,
        SetMaxBasalLimitResponse.self,
        SetMaxBolusLimitRequest.self,
        SetMaxBolusLimitResponse.self,
        SetModesRequest.self,
        SetModesResponse.self,
        SetPumpAlertSnoozeRequest.self,
        SetPumpAlertSnoozeResponse.self,
        SetPumpSoundsRequest.self,
        SetPumpSoundsResponse.self,
        SetQuickBolusSettingsRequest.self,
        SetQuickBolusSettingsResponse.self,
        SetSleepScheduleRequest.self,
        SetSleepScheduleResponse.self,
        SetTempRateRequest.self,
        SetTempRateResponse.self,
        StartDexcomG6SensorSessionRequest.self,
        StartDexcomG6SensorSessionResponse.self,
        StopDexcomCGMSensorSessionRequest.self,
        StopDexcomCGMSensorSessionResponse.self,
        StopTempRateRequest.self,
        StopTempRateResponse.self,
        SuspendPumpingRequest.self,
        SuspendPumpingResponse.self,
        TempRateRequest.self,
        TempRateResponse.self,
        TimeSinceResetRequest.self,
        TimeSinceResetResponse.self,
        UnknownMobiOpcode110Request.self,
        UnknownMobiOpcode110Response.self,
        UnknownMobiOpcode20Request.self,
        UnknownMobiOpcode20Response.self,
        UnknownMobiOpcode30Request.self,
        UnknownMobiOpcode30Response.self,
        UnknownMobiOpcodeNeg124Request.self,
        UnknownMobiOpcodeNeg124Response.self,
        UnknownMobiOpcodeNeg66Request.self,
        UnknownMobiOpcodeNeg66Response.self,
        UnknownMobiOpcodeNeg70Request.self,
        UnknownMobiOpcodeNeg70Response.self,
    ]

    public static let all: [MessageMetadata] = allTypes.compactMap(MessageMetadata.init)

    private static let metadataByName: [String: MessageMetadata] = {
        var dict: [String: MessageMetadata] = [:]
        for meta in all {
            dict[meta.name.lowercased()] = meta
            if let simple = meta.name.split(separator: ".").last {
                let key = String(simple).lowercased()
                dict[key] = meta
            }
        }
        return dict
    }()

    public static func metadata(forName name: String) -> MessageMetadata? {
        metadataByName[name.lowercased()]
    }

    public static func matches(opCode: UInt8, characteristic: CharacteristicUUID? = nil) -> [MessageMetadata] {
        all.filter { meta in
            guard meta.opCode == opCode else { return false }
            if let characteristic = characteristic {
                return meta.characteristic == characteristic
            }
            return true
        }
    }

    public static func bestMatches(opCode: UInt8, characteristic: CharacteristicUUID?, payloadLength: Int) -> [MessageMetadata] {
        var candidates = matches(opCode: opCode, characteristic: characteristic)
        let filtered = candidates.filter { $0.matches(payloadLength: payloadLength) }
        if !filtered.isEmpty {
            candidates = filtered
        }
        return candidates
    }

    public static func names() -> [String] {
        all.map { $0.name }.sorted()
    }
}
