name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Install Carthage
        run: brew install carthage
      - name: Bootstrap Carthage dependencies
        run: |
          set -o pipefail
          ./carthage.sh bootstrap --platform iOS --no-use-binaries --use-xcframeworks --verbose 2>&1 | tee carthage.log
      - name: Upload Carthage log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: carthage-xcodebuild.log
          path: carthage.log
      - name: Build TandemKit XCFramework
        run: |
          xcodebuild archive \
            -project TandemKit.xcodeproj -scheme TandemKit \
            -destination 'generic/platform=iOS' \
            -archivePath build/ios \
            SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
          xcodebuild archive \
            -project TandemKit.xcodeproj -scheme TandemKit \
            -destination 'generic/platform=iOS Simulator' \
            -archivePath build/ios-sim \
            SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
          xcodebuild -create-xcframework \
            -framework build/ios.xcarchive/Products/Library/Frameworks/TandemKit.framework \
            -framework build/ios-sim.xcarchive/Products/Library/Frameworks/TandemKit.framework \
            -output build/TandemKit.xcframework
          cd build
          zip -r TandemKit.xcframework.zip TandemKit.xcframework
      - name: Upload TandemKit XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: TandemKit.xcframework
          path: build/TandemKit.xcframework.zip
