name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Carthage
        run: brew install carthage
      - name: Bootstrap Carthage dependencies
        run: ./carthage.sh bootstrap --platform iOS --no-use-binaries
      - name: Build TandemKit
        run: xcodebuild -project TandemKit.xcodeproj -scheme TandemKit -destination 'generic/platform=iOS' -configuration Release CODE_SIGNING_ALLOWED=NO build
